function [] =  checkPulsewaveParamsFromTxt(path)

[~,filename,~] = fileparts(path);
filename_txt = 'InputPulsewaveParams.txt';
dir_path_txt = fullfile(path,'txt');


%filename_txt = strcat(filename,filename_txt);
txt_exists = exist(fullfile(dir_path_txt,filename_txt));


if txt_exists
    disp("Parameter file already exists")

else
    disp("Parameter file does not exist, writing in process")
    %Initialisation
    k = 1;
    radius_ratio = 0.18;
    resistivity_gaussFiltSigma = 0.7;
    resistivity_satAmp = 0.75;
    resistivity_minTolVal = 0.02;
    resistivity_maxTolVal = 0.98;
    resistivity_gamma = 0.7;
    oneCycle_Ninterp = 64;
    oneCycle_outNoiseThreshold = 2;
    oneCycle_dataReliabilityThreshold = 50; %percent
    arteryMask_vesselness_sigma = 3;
    arteryMask_vesselness_beta = 0.8;
    arteryMask_bin_threshold = 0.2; 
    arteryMask_magicwand_nb_of_area_vessels = 2;
    arteryMask_magicwand_nb_of_area_artery = 4;
    arteryMask_choroidCorrThreshold = 0.2;
    centralRetinal_arteryThreshold = 3;
    centralRetinal_veinThreshold = -3;
    centralRetinal_backgndThreshold = 2 ;
    vesselMask_stdBinTreshold = 0.4 ;
    cropSection_scaleFactorWidth = 3 ;
    cropSection_scaleFactorSize = 0.004 ;
    cropSection_maskThreshold = 0.01 ;
    cropSection_pixelSize = 0.0102 ;
    elasWave_nDomFreq = 2 ;
    elasWave_pixelSize = 6/1535 ;
    elasWave_gaussFiltPadding = 0 ;
    elasWave_butterFiltOrder = 10 ;
    elasWave_butterFiltBand = 3 ;
    systoleThreshold = 0.7 ;
    flatField_gwRatio = 0.07 ;
    flatField_border = 0.25 ;
    flatField_borderDMap = 0.33 ;
    flatField_borderPulseAnal = 0 ;
    flowRate_gaussFiltPadding = 0 ;
    flowRate_yelorRangeHSV = 0.18 ;
    flowRate_cydblueRangeHSV = 0.68 ;
    flowRate_minTolVal = 0.2 ; % ou 0.1 une fois
    flowRate_maxTolVal = 0.98 ; % ou 0.99 une fois
    flowRate_sliceHalfThickness = 10 ;
    pupilRadius = 2 ;
    iris2retinaDist = 20 ;
    theta = 0.05 ;
    opticalIndex = 1.35 ;
    lambda = 852e-9 ;
    pulseAnal_dataReliabilityFactor = 0.5 ;
    pulseAnal_peakHeightThreshold = 0.7 ;
    pulseAnal_outNoiseThreshold = 4 ;
    pulseAnal_blurScaleFactor = 100 ;
    pulseAnal_frameMinDiastole = 0.1 ;
    pulseAnal_framePeakSystole = 0.1 ;
    pulseAnal_exp = exp(1) ;
    trWavelength_f0 = 150 ;
    trWavelength_r0 = 150 ;
    video2vessels_radiusRatio = 0.27 ;
    video2vessels_gaussFiltPadding = 0 ;
    video2vessels_gaussFiltFactor = 0.25 ;
    viscosity_Ninterp = 100 ;
    viscosity_interpParam = 2 ;
    viscosity_interpSizeFactor = 4 ;
    viscosity_projimThreshold = 0.1 ;
    viscosity_fctnFactor = 0.7 ;
    viscosity_fitMatrix = 0 ;
    viscosity_listParamA = 1.459 ;
    viscosity_listParamB = 0.017 ;
    nbSides = 120 ;
    mkdir(dir_path_txt);
    fileID = fopen(fullfile(dir_path_txt, filename_txt),'w');
    fprintf(fileID,[...
    'Value of the interpolation parameter :\n%d\n' ...
    'Radius ratio :\n%d\n', ...
    ...
    'Resistivity index\n', ... %create_resistivity_index
    'Gaussian filter sigma :\n%f\n', ... % line 15
    'Amplitude saturation  ponderation :\n%f\n', ... % line 33 MUST be in [0 1] 
    'Tolerante value minimum :\n%f\n', ... % line 52
    'Tolerante value maximum :\n%f\n', ... % line 52
    'Gamma :\n%f\n', ... %line 69
    ...
    '\nCreation of one cycle\n', ... %create_one_cycle
    'Number of interpolation :\n%f\n', ... % line 8
    'Out of noise treshold :\n%f\n', ... % line 41
    'Data reliability index treshold :\n%f\n', ... % line 75
    ...
    '\nCreation of the artery mask\n', ... %createArteryMask
    'Vesselnes parameter sigma :\n%f\n', ... % line 8
    'Vesselnes parameter beta :\n%f\n', ... % line 9
    'Binarization treshold :\n%f\n', ... % line 10
    'Number of segmented area detected for vessels :\n%f\n', ... % line 12
    'Number of segmented area detected for artery :\n%f\n', ... % line 12
    'Choroid correlation threshold :\n%f\n', ... % line 55
    ...
    '\nCentral retina mask\n', ... %createCentraleRetinalArteryVeinMask
    'Central retina artery treshold :\n%f\n', ... % line 8
    'Central retina vein treshold :\n%f\n', ... % line 9
    'Central retina background treshold :\n%f\n', ... % line 10
    ...
    '\nVessel mask\n', ... %createVesselMask
    'Standard binarization treshold :\n%f\n', ... % line 8
    ...
    '\nCrop section analysis\n', ... %crop_section_analysis
    'Scale factor width :\n%f\n', ... % line 18
    'Scale factor size :\n%f\n', ... % line 63
    'Mask slice treshold :\n%f\n', ... % line 79
    'Pixel size ? :\n%f\n', ... % line 101 see comment in fonction
    ...
    '\nElastic waves\n', ... %fetectElasticWave
    'Number of dominant frequency :\n%f\n', ... % line 3
    'Pixel size :\n%f\n', ... % line 4
    'Gaussian filter padding :\n%f\n', ... % line 4
    'Butterworth filter order :\n%f\n', ... % line 42
    'Butterworth filter thickness band :\n%f\n', ... % line 42
    ...
    '\nSystole\n', ... %find_systole_index
    'Systole threshold :\n%f\n', ... % line 52
    ...
    '\nFlat field correction\n', ... %flat_field_correction
    'GW ratio :\n%f\n', ...
    'Border :\n%f\n', ...
    'Border dMAP :\n%f\n', ...
    'Border PulseAnalisys :\n%f\n', ...
    ...
    '\nFlow rate\n', ... %flow_rate
    'Gaussian filter padding :\n%f\n', ... % line 19
    'Yellow-orange range HSV :\n%f\n', ... % line 72-102-121-142-158
    'Cyan-dark blue range HSV :\n%f\n', ... % line 73-103-122
    'Tolerante value minimum :\n%f\n', ... % line 77-98-106-126
    'Tolerante value maximum :\n%f\n', ... % line 77-98-106-126 different smtimes
    'Slice half thickness :\n%f\n', ... % line 199
    ...
    '\nPulse analisys\n', ... %pulseanalisys
    'Radius pupil :\n%f\n', ... % line 25
    'Distance iris-retina :\n%f\n', ... % line 26
    'Theta :\n%f\n', ... % line 27
    'Optical index :\n%f\n', ... % line 28
    'Lambda :\n%f\n', ... % line 29
    'Data reliatibility factor ? :\n%f\n', ... % line 148
    'Peak height treshold :\n%f\n', ... % line 207
    'Out of noise treshold :\n%f\n', ... % line 215 same as create_one_cycle ?
    'Blur scale factor :\n%f\n', ... % line 368-369
    'Frame percentage before minimum of diastole :\n%f\n', ... % line 636 ? 
    'Frame percentage around peak systole :\n%f\n', ... % line 653 ? 
    'exponentiel 1 ? :\n%f\n', ... % line 721 ? 
    ...
    '\nWavelength\n', ... %TRwavelength
    'F0 :\n%f\n', ... % line 5
    'R0 :\n%f\n', ... % line 13
    ...
    '\nVessels video\n', ... %video2vessels
    'Radius ratio factor :\n%f\n', ... % line 8
    'Gaussian filter padding :\n%f\n', ... % line 10
    'Gaussian filter factor :\n%f\n', ... % line 10
    ...
    '\nViscosity\n', ... %viscosity
    'Number of interpolation :\n%f\n', ... % line 10
    'Interpolation parameter :\n%f\n', ... % line 12
    'Interpolation size factor :\n%f\n', ... % line 21
    'Image projection treshold :\n%f\n', ... % line 41
    'Viscosity function factor :\n%f\n', ... % line 89
    'Fit function parameter (matrix) :\n%f\n', ... % line 95
    'Viscosity list parameter a :\n%f\n', ... % line 123
    'Viscosity list parameter b :\n%f\n', ... % line 123
    ...
    '\nOther\n', ... 
    'Number of sides :\n%f\n', ... % video2vessel line 3 and flow_rate  line 11
    ], ...
    k, ...
    radius_ratio, ...
    resistivity_gaussFiltSigma, ...
    resistivity_satAmp, ...
    resistivity_minTolVal, ...
    resistivity_maxTolVal, ...
    resistivity_gamma, ...
    oneCycle_Ninterp, ...
    oneCycle_outNoiseThreshold, ...
    oneCycle_dataReliabilityThreshold, ...
    arteryMask_vesselness_sigma, ...
    arteryMask_vesselness_beta, ...
    arteryMask_bin_threshold, ...
    arteryMask_magicwand_nb_of_area_vessels, ...
    arteryMask_magicwand_nb_of_area_artery, ...
    arteryMask_choroidCorrThreshold, ...
    centralRetinal_arteryThreshold, ...
    centralRetinal_veinThreshold, ...
    centralRetinal_backgndThreshold, ...
    vesselMask_stdBinTreshold, ...
    cropSection_scaleFactorWidth, ...
    cropSection_scaleFactorSize, ...
    cropSection_maskThreshold, ...
    cropSection_pixelSize, ...
    elasWave_nDomFreq, ...
    elasWave_pixelSize, ...
    elasWave_gaussFiltPadding, ...
    elasWave_butterFiltOrder, ...
    elasWave_butterFiltBand, ...
    systoleThreshold, ...
    flatField_gwRatio, ...
    flatField_border, ...
    flatField_borderDMap, ...
    flatField_borderPulseAnal, ...
    flowRate_gaussFiltPadding, ...
    flowRate_yelorRangeHSV, ...
    flowRate_cydblueRangeHSV, ...
    flowRate_minTolVal, ...
    flowRate_maxTolVal, ...
    flowRate_sliceHalfThickness, ...
    pupilRadius, ...
    iris2retinaDist, ...
    theta, ...
    opticalIndex, ...
    lambda, ...
    pulseAnal_dataReliabilityFactor, ...
    pulseAnal_peakHeightThreshold, ...
    pulseAnal_outNoiseThreshold, ...
    pulseAnal_blurScaleFactor, ...
    pulseAnal_frameMinDiastole, ...
    pulseAnal_framePeakSystole, ...
    pulseAnal_exp, ...
    trWavelength_f0, ...
    trWavelength_r0, ...
    video2vessels_radiusRatio, ...
    video2vessels_gaussFiltPadding, ...
    video2vessels_gaussFiltFactor, ...
    viscosity_Ninterp, ...
    viscosity_interpParam, ...
    viscosity_interpSizeFactor, ...
    viscosity_projimThreshold, ...
    viscosity_fctnFactor, ...
    viscosity_fitMatrix, ...
    viscosity_listParamA, ...
    viscosity_listParamB, ...
    nbSides);
    fclose(fileID) ;
end
end
    

